### ISSUE TITLE
Invalid build number didn't get handled

### ISSUE THREAD

**Issue by nikhil-179** [EviveHealth/clowder#9]
The following log was observed:
**2019-07-25 12:02:26,400 ERROR NetworkCalls:257 - Unable to fetch eet_pipeline_test with build number 12q3w45r6tijw4sedrftgy8huji0ko-lp4wsedrtyhi0ko-lp=rzextuiop,[ - invalid liter
al for int() with base 10: '12q3w45r6tijw4sedrftgy8huji0ko-lp4wsedrtyhi0ko-lp=rzextuiop,['
Traceback (most recent call last):
  File "/opt/clowder/blueprints/NetworkCalls.py", line 247, in get_build_info
    build_info = sess.get_job(app_name).get_build(int(build_number))
ValueError: invalid literal for int() with base 10: '12q3w45r6tijw4sedrftgy8huji0ko-lp4wsedrtyhi0ko-lp=rzextuiop,['**

**Comment by saijal-chauhan** [comment]
2019-07-25 12:09:10,708 ERROR NetworkCalls:253 - Build number 583 not found for application ibot
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jenkinsapi/job.py", line 414, in get_build
    url = self.get_build_dict()[buildnumber]
KeyError: 583

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/clowder/blueprints/NetworkCalls.py", line 247, in get_build_info
    build_info = sess.get_job(app_name).get_build(int(build_number))
  File "/usr/lib/python3.6/site-packages/jenkinsapi/job.py", line 417, in get_build
    raise NotFound('Build #%s not found' % buildnumber)
jenkinsapi.custom_exceptions.NotFound: Build #583 not found
